export declare const RED = "#ee0a24";
export declare const BLUE = "#1989fa";
export declare const GREEN = "#07c160";
export declare const WHITE = "#fff";
export declare const BORDER = "van-hairline";
export declare const BORDER_TOP: string;
export declare const BORDER_LEFT: string;
export declare const BORDER_RIGHT: string;
export declare const BORDER_BOTTOM: string;
export declare const BORDER_SURROUND: string;
export declare const BORDER_TOP_BOTTOM: string;
export declare const BORDER_UNSET_TOP_BOTTOM: string;
